import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import 'animate.css';
import AllCoursesPage from "./all-courses/page";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    
      suppressHydrationWarning
    >
      <body className="min-h-full max-w-full p-4 mx-auto flex flex-col suppressHydrationWarning={true}">
     
     <Navbar></Navbar>
       <main>
       {/* <AllCoursesPage></AllCoursesPage> */}
         {children}
         {/* <Animation></Animation> */}
         
       </main>

       <Footer></Footer>
        
        </body>
    </html>
  );
}
